### ISSUE TITLE
Can't open Fenced code blocks window when ``` is not in first column

### ISSUE THREAD

**Issue by ik0r** [amiorin/vim-fenced-code-blocks#2]
``````
1. foo

    ```js
    var a= '1';
    function abc(){}
    ```
2. bar
3. baz
``````

In above example, when cursor is on code blocks, `:E` will not open Fenced code blocks window

And in below Fenced code blocks window will open

``````
1. foo

```js
var a= '1';
function abc(){}
```
2. bar
3. baz
``````

**Comment by dhulihan** [comment]
This would be really nice. I used indented code blocks in markdown quite often.
